version: "2"
services:
  hello-world:
    image: "node:10.15.3-alpine"
    working_dir: /home/node/app
    volumes:
      - ./01-hello-world:/home/node/app
    ports:
      - "8080:80"
    command: "npm start"
  s3-list:
    image: "node:10.15.3-alpine"
    working_dir: /home/node/app
    volumes:
      - ./02-s3-list:/home/node/app
    ports:
      - "8081:80"
    command: "npm start"
    environment:
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_REGION=$AWS_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
